### ISSUE TITLE
Crew screen X button is not clickable everywhere on stand-alone program.

### ISSUE THREAD

**Issue by Froginator45** [Thorium-Sim/thorium-nova#237] opened 2022-02-25 00:29 UTC
Crew screen X button does not have the full clickable area on stand-alone program on windows 10 as it does on chrome.

The clickable area is shown in red:
![image](https://user-images.githubusercontent.com/19561600/155629974-4844d3ab-c887-465d-aac2-544c2d2f2eb4.png)

Changing the size of the window does not affect the clickable area.

The X box is all clickable and works perfectly on chrome.

**Comment by 1deejay** [comment] 2022-12-29 07:37
I'm not sure how to recreate this issue in the dev environment. The good news is the issue is still not on chrome and it's not on firefox either.

**Comment by 1deejay** [comment] 2022-12-29 07:39
You can also click off of the box to go back, do we need the X button there at all? Current UX is boxes like that you just click off of to close and it works normally.
I think this also depends on if that function is in the window that the program creates.

**Comment by alexanderson1993** [comment] 2023-04-10 23:30
This appears to be working correctly in the latest alpha. Closing.

**Closed as completed by alexanderson1993** 2023-04-10 23:30 UTC
Labels: Bug, approved
